apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog-app.fullname" . }}-backend
  labels:
    app: {{ include "blog-app.name" . }}
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app: {{ include "blog-app.name" . }}
    component: backend
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: 5000
      protocol: TCP
