apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog-app.fullname" . }}-frontend
  labels:
    app: {{ include "blog-app.name" . }}
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: {{ include "blog-app.name" . }}
    component: frontend
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.service.frontend.nodePort | default 30000 }}
