apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "blog-app.fullname" . }}-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.storage }}
  storageClassName: {{ .Values.mongodb.storageClass }}
